CREATE TABLE [dbo].[Foglalas4](
	[FOGLALAS_PK] [int] MASKED WITH (FUNCTION = 'random(1,3)') NOT NULL,
	[UGYFEL_FK] [nvarchar](20) MASKED WITH (Function = 'partial(1,"XXX",1)') NOT NULL,
	[SZOBA_FK] [int] NOT NULL,
	[METTOL] [date] MASKED WITH (Function = 'default()') NOT NULL,
	[MEDDIG] [date] NOT NULL,
	[FELNOTT_SZAM] [int]  MASKED WITH (FUNCTION = 'random(2,6)') NOT NULL,
	[GYERMEK_SZAM] [int] NOT NULL,
 CONSTRAINT [PK_Foglalas4] PRIMARY KEY CLUSTERED 
(
	[FOGLALAS_PK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]